// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/lucasd-coder/fast-feet/auth-service/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/lucasd-coder/fast-feet/auth-service/pkg/pb"
)

// Service_internal_domain_auth is an autogenerated mock type for the Service type
type Service_internal_domain_auth struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, pld
func (_m *Service_internal_domain_auth) CreateUser(ctx context.Context, pld *auth.Register) (*pb.RegisterResponse, error) {
	ret := _m.Called(ctx, pld)

	var r0 *pb.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.Register) (*pb.RegisterResponse, error)); ok {
		return rf(ctx, pld)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.Register) *pb.RegisterResponse); ok {
		r0 = rf(ctx, pld)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.Register) error); ok {
		r1 = rf(ctx, pld)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByEmail provides a mock function with given fields: ctx, pld
func (_m *Service_internal_domain_auth) FindUserByEmail(ctx context.Context, pld *auth.FindUserByEmail) (*pb.GetUserResponse, error) {
	ret := _m.Called(ctx, pld)

	var r0 *pb.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.FindUserByEmail) (*pb.GetUserResponse, error)); ok {
		return rf(ctx, pld)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.FindUserByEmail) *pb.GetUserResponse); ok {
		r0 = rf(ctx, pld)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.FindUserByEmail) error); ok {
		r1 = rf(ctx, pld)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoles provides a mock function with given fields: ctx, pld
func (_m *Service_internal_domain_auth) GetRoles(ctx context.Context, pld *auth.GetUserID) (*pb.GetRolesResponse, error) {
	ret := _m.Called(ctx, pld)

	var r0 *pb.GetRolesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.GetUserID) (*pb.GetRolesResponse, error)); ok {
		return rf(ctx, pld)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.GetUserID) *pb.GetRolesResponse); ok {
		r0 = rf(ctx, pld)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetRolesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.GetUserID) error); ok {
		r1 = rf(ctx, pld)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsActiveUser provides a mock function with given fields: ctx, pld
func (_m *Service_internal_domain_auth) IsActiveUser(ctx context.Context, pld *auth.GetUserID) (*pb.IsActiveUserResponse, error) {
	ret := _m.Called(ctx, pld)

	var r0 *pb.IsActiveUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.GetUserID) (*pb.IsActiveUserResponse, error)); ok {
		return rf(ctx, pld)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *auth.GetUserID) *pb.IsActiveUserResponse); ok {
		r0 = rf(ctx, pld)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.IsActiveUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *auth.GetUserID) error); ok {
		r1 = rf(ctx, pld)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService_internal_domain_auth creates a new instance of Service_internal_domain_auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService_internal_domain_auth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service_internal_domain_auth {
	mock := &Service_internal_domain_auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
