// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	context "context"

	pb "github.com/lucasd-coder/fast-feet/business-service/pkg/pb"
	mock "github.com/stretchr/testify/mock"
)

// Repository_internal_domain_user is an autogenerated mock type for the Repository type
type Repository_internal_domain_user struct {
	mock.Mock
}

// FindByCpf provides a mock function with given fields: ctx, req
func (_m *Repository_internal_domain_user) FindByCpf(ctx context.Context, req *pb.UserByCpfRequest) (*pb.UserResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *pb.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UserByCpfRequest) (*pb.UserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UserByCpfRequest) *pb.UserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.UserByCpfRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: ctx, req
func (_m *Repository_internal_domain_user) FindByEmail(ctx context.Context, req *pb.UserByEmailRequest) (*pb.UserResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *pb.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UserByEmailRequest) (*pb.UserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UserByEmailRequest) *pb.UserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.UserByEmailRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, req
func (_m *Repository_internal_domain_user) Save(ctx context.Context, req *pb.UserRequest) (*pb.UserResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *pb.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UserRequest) (*pb.UserResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UserRequest) *pb.UserResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.UserRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository_internal_domain_user creates a new instance of Repository_internal_domain_user. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository_internal_domain_user(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository_internal_domain_user {
	mock := &Repository_internal_domain_user{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
