// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: request/register.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RegisterHandler_CreateUser_FullMethodName = "/pb.RegisterHandler/CreateUser"
)

// RegisterHandlerClient is the client API for RegisterHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterHandlerClient interface {
	CreateUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registerHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterHandlerClient(cc grpc.ClientConnInterface) RegisterHandlerClient {
	return &registerHandlerClient{cc}
}

func (c *registerHandlerClient) CreateUser(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, RegisterHandler_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterHandlerServer is the server API for RegisterHandler service.
// All implementations must embed UnimplementedRegisterHandlerServer
// for forward compatibility
type RegisterHandlerServer interface {
	CreateUser(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedRegisterHandlerServer()
}

// UnimplementedRegisterHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedRegisterHandlerServer struct {
}

func (UnimplementedRegisterHandlerServer) CreateUser(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedRegisterHandlerServer) mustEmbedUnimplementedRegisterHandlerServer() {}

// UnsafeRegisterHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterHandlerServer will
// result in compilation errors.
type UnsafeRegisterHandlerServer interface {
	mustEmbedUnimplementedRegisterHandlerServer()
}

func RegisterRegisterHandlerServer(s grpc.ServiceRegistrar, srv RegisterHandlerServer) {
	s.RegisterService(&RegisterHandler_ServiceDesc, srv)
}

func _RegisterHandler_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterHandlerServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegisterHandler_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterHandlerServer).CreateUser(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterHandler_ServiceDesc is the grpc.ServiceDesc for RegisterHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegisterHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RegisterHandler",
	HandlerType: (*RegisterHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _RegisterHandler_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request/register.proto",
}
